version: '3'

services:
  
  jira:
    container_name: ${DOCKER_ENV_NAME}-jira
    image: ${IMAGE_VERSION_JIRA}
    volumes:
     - jira1-volume:/var/atlassian/application-data/jira
    # ports:
    # - "8080:8080"
    depends_on:
     - postgres
     - pgadmin
     - grafana
     - prometheus
     - nodered
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     - JVM_MAXIMUM_MEMORY=2g
     - SET_PERMISSIONS=false

  postgres:
    container_name: ${DOCKER_ENV_NAME}-postgres
    image: ${IMAGE_VERSION_POSTGRES}
    volumes:
     - postgres1-volume:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Incorrect

  pgadmin:
    container_name: ${DOCKER_ENV_NAME}-pgadmin
    image: ${IMAGE_VERSION_PGADMIN}
    volumes:
     - pgadmin1-volume:/var/lib/pgadmin
    ports:
    - "5050:5050"
    depends_on:
     - postgres
    environment:
     - SERVER_PROXY_NAME=pgadmin.internal
     - SERVER_PROXY_PORT=80
     - PGADMIN_LISTEN_PORT=5050
     - SERVER_SCHEME=http
     - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.internal
     - PGADMIN_DEFAULT_PASSWORD=Incorrect

  nodered:
    container_name: ${DOCKER_ENV_NAME}-nodered
    volumes:
     - nodered1-volume:/data
    image: ${IMAGE_VERSION_NODERED}
    ports:
    - "1880:1880"
  
  grafana:
    container_name: ${DOCKER_ENV_NAME}-grafana
    image: ${IMAGE_VERSION_GRAFANA}
    volumes:
      - grafana1data-volume:/var/lib/grafana
      - grafana1conf-volume:/etc/grafana
    ports:
      - "3000:3000"

  prometheus:
    container_name: ${DOCKER_ENV_NAME}-prometheus
    image: ${IMAGE_VERSION_PROMETHEUS}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus1-volume:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--web.enable-admin-api'
    - '--web.enable-lifecycle'
    ports:
     - "9090:9090"

  nginx:
    container_name: ${DOCKER_ENV_NAME}-nginx
    image: ${IMAGE_VERSION_NGINX}
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - jira
     - pgadmin
     - nodered
     - grafana
     - prometheus
    ports:
     - "80:80"
    networks:
      default:
        aliases:
         - jira.internal
         - pgadmin.internal
         - nodered.internal
         - grafana.internal
         - prometheus.internal

volumes:
    nodered1-volume:
    jira1-volume:
    pgadmin1-volume:
    postgres1-volume:
    prometheus1-volume:
    grafana1conf-volume:
    grafana1data-volume:

