version: '3'
services:
  jira:
    container_name: jira
    image: atlassian/jira-software
    volumes:
     - jira-volume:/var/atlassian/application-data/jira
    ports:
     - "8080:8080"
    depends_on:
     - postgres
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     - JVM_MAXIMUM_MEMORY=2g
     - SET_PERMISSIONS=false

  postgres:
    container_name: postgres
    image: postgres:10
    volumes:
     - postgres-volume:/var/lib/postgresql
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Incorrect

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
     - pgadmin-volume:/var/lib/pgadmin
    ports:
     - "5050:5050"
    depends_on:
     - postgres
    environment:
     - SERVER_PROXY_NAME=pgadmin.internal
     - SERVER_PROXY_PORT=80
     - PGADMIN_LISTEN_PORT=5050
     - SERVER_SCHEME=http
     - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.internal
     - PGADMIN_DEFAULT_PASSWORD=Incorrect

  nodered:
    container_name: nodered
    volumes:
     - nodered-volume:/data
    image: nodered/node-red:latest-minimal
    ports:
     - "1880:1880"
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - jira
     - pgadmin
    ports:
     - "80:80"
    networks:
      default:
        aliases:
         - jira.internal
         - pgadmin.internal
         - nodered.internal
volumes:
    nodered-volume:
    jira-volume:
    pgadmin-volume:
    postgres-volume:
