version: '3' 
services: 
  jira:
    container_name: jira 
    image: atlassian/jira-software:latest
    volumes: 
      - ./jira:/var/atlassian/application-data/jira
    depends_on:
     - postgres
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     - JVM_MAXIMUM_MEMORY=2g
     - SET_PERMISSIONS=false

  # confluence: 
  #   container_name: confluence
  #   image: atlassian/confluence-server:latest
  #   volumes:
  #    - ./confluence:/var/atlassian/application-data/confluence 
  #   depends_on:
  #    - postgres
  #   environment: 
  #    - ATL_PROXY_NAME=confluence.internal
  #    - ATL_PROXY_PORT=80
  #    - ATL_TOMCAT_SCHEME=http
  #    - JVM_MAXIMUM_MEMORY=2g
  #    - SET_PERMISSIONS=false

  # bitbucket: 
  #   container_name: bitbucket 
  #   image: atlassian/bitbucket-server:latest
  #   volumes:
  #    - ./bitbucket:/var/atlassian/application-data/bitbucket
  #   depends_on:
  #    - postgres
  #   environment: 
  #    - SERVER_PROXY_NAME=bitbucket.internal
  #    - SERVER_PROXY_PORT=80
  #    - SERVER_SCHEME=http     
  #    - JVM_MAXIMUM_MEMORY=2g
  #    - SET_PERMISSIONS=false

  postgres:
    container_name: postgres
    image: postgres:10
    volumes:
     - ./postgres:/var/lib/postgresql
#     - ./
    environment:
     - POSTGRES_USER=postgres 
     - POSTGRES_PASSWORD=incorrect

  pgadmin:
    container_name: pgadmin 
    image: dpage/pgadmin4
    volumes: 
     - ./pgadmin:/var/lib/pgadmin
    depends_on:
     - postgres 
    environment: 
     - SERVER_PROXY_NAME=pgadmin.internal
     - SERVER_PROXY_PORT=80
     - PGADMIN_LISTEN_PORT=5050
     - SERVER_SCHEME=http 
     - PGADMIN_DEFAULT_EMAIL=pgadmin@gadmin.internal
     - PGADMIN_DEFAULT_PASSWORD=incorrect

  nodered:
    container_name: nodered
    volumes: 
     - ./nodered:/data
    image: nodered/node-red:latest-minimal

  nginx: 
    container_name: nginx 
    image: nginx:latest 
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on: 
     - jira 
    #  - confluence 
    #  - bitbucket 
     - pgadmin
    ports: 
     - "80:80" 
    networks: 
      default: 
        aliases:
         - jira.internal
        #  - confluence.internal
        #  - bitbucket.internal
         - pgadmin.internal
         - nodered.internal

      
